name: Build

on:
  push:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: codestyle
      run: git ls-files *.{c,h} | xargs clang-format -i --verbose src/main/geometry.c src/lib/lib_calc_trans.c src/lib/libmainchek.c src/lib/*.h
